import { dirname } from "path";
import { fileURLToPath } from "url";
import { FlatCompat } from "@eslint/eslintrc";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({
  baseDirectory: __dirname,
});

const eslintConfig = [
  {
    rules: {
      // Disable all ESLint rules
      "@typescript-eslint/no-explicit-any": "off",
      "@typescript-eslint/no-unused-vars": "off",
      "no-unused-vars": "off",
      "no-console": "off",
      "prefer-const": "off",
      "no-var": "off",
      "no-undef": "off",
      "no-redeclare": "off",
      "no-duplicate-imports": "off",
      "no-unreachable": "off",
      "no-constant-condition": "off",
      "no-empty": "off",
      "no-extra-semi": "off",
      "no-irregular-whitespace": "off",
      "no-multiple-empty-lines": "off",
      "no-trailing-spaces": "off",
      "no-mixed-spaces-and-tabs": "off",
      "indent": "off",
      "quotes": "off",
      "semi": "off",
      "comma-dangle": "off",
      "object-curly-spacing": "off",
      "array-bracket-spacing": "off",
      "computed-property-spacing": "off",
      "func-call-spacing": "off",
      "key-spacing": "off",
      "keyword-spacing": "off",
      "space-before-blocks": "off",
      "space-before-function-paren": "off",
      "space-in-parens": "off",
      "space-infix-ops": "off",
      "space-unary-ops": "off",
      "spaced-comment": "off",
      "arrow-spacing": "off",
      "block-spacing": "off",
      "brace-style": "off",
      "comma-spacing": "off",
      "comma-style": "off",
      "computed-property-spacing": "off",
      "eol-last": "off",
      "func-call-spacing": "off",
      "key-spacing": "off",
      "keyword-spacing": "off",
      "linebreak-style": "off",
      "lines-around-comment": "off",
      "lines-between-class-members": "off",
      "max-len": "off",
      "max-lines": "off",
      "max-lines-per-function": "off",
      "max-statements": "off",
      "multiline-comment-style": "off",
      "new-cap": "off",
      "new-parens": "off",
      "newline-after-var": "off",
      "newline-before-return": "off",
      "newline-per-chained-call": "off",
      "no-array-constructor": "off",
      "no-bitwise": "off",
      "no-continue": "off",
      "no-inline-comments": "off",
      "no-lonely-if": "off",
      "no-multi-assign": "off",
      "no-multiple-empty-lines": "off",
      "no-nested-ternary": "off",
      "no-new-object": "off",
      "no-plusplus": "off",
      "no-tabs": "off",
      "no-trailing-spaces": "off",
      "no-unneeded-ternary": "off",
      "no-whitespace-before-property": "off",
      "nonblock-statement-body-position": "off",
      "object-curly-newline": "off",
      "object-curly-spacing": "off",
      "object-property-newline": "off",
      "one-var": "off",
      "one-var-declaration-per-line": "off",
      "operator-assignment": "off",
      "operator-linebreak": "off",
      "padded-blocks": "off",
      "padding-line-between-statements": "off",
      "quote-props": "off",
      "quotes": "off",
      "require-jsdoc": "off",
      "semi": "off",
      "semi-spacing": "off",
      "semi-style": "off",
      "sort-keys": "off",
      "sort-vars": "off",
      "space-before-blocks": "off",
      "space-before-function-paren": "off",
      "space-in-parens": "off",
      "space-infix-ops": "off",
      "space-unary-ops": "off",
      "spaced-comment": "off",
      "switch-colon-spacing": "off",
      "template-tag-spacing": "off",
      "unicode-bom": "off",
      "wrap-iife": "off",
      "wrap-regex": "off",
      "yield-star-spacing": "off"
    },
    ignores: [
      "**/*"
    ],
  },
];

export default eslintConfig;
